### ISSUE TITLE
agent_profiles.yaml content

### ISSUE THREAD

**Issue by EvaVitas** [longevity-genie/just-agents#16]
Dear Anton,

I hope this email finds you well. I’ve been trying to use just-agents to explore its capabilities with my OpenAI API key, following your GitHub documentation. I wanted to share my experience and some issues I encountered.

Installation Process
I successfully installed just-agents (version 0.6.0) on Ubuntu using Poetry after some initial hiccups:

I had to upgrade Poetry from 1.1.12 to 2.1.1 due to compatibility issues with pyproject.toml (e.g., group and priority not supported in older versions).
The dependency installation (107 packages) worked fine after resolving Poetry path conflicts.
 

Testing Experience
I aimed to run a simple WebAgent with gpt-3.5-turbo using run-server-command. The README on GitHub’s first page suggests a basic usage:

# Basic usage

run-agent agent_profiles.yaml

However, I couldn’t find an agent_profiles.yaml file in the repository, so I created one myself:

 

```yaml

 

agent:

  type: "WebAgent"

  llm_options:

    model: "gpt-3.5-turbo"

    api_key: "${OPENAI_API_KEY}"

    api_base: "https://api.openai.com/v1"

    temperature: 0.7

  role: "You are a helpful assistant"

  goal: "Answer questions clearly"

  task: "Respond to user queries"

  memory:

    type: "simple"

```

I set OPENAI_API_KEY in .env and ran:

 

```bash

run-agent run-server-command agent_profiles.yaml

```

Unfortunately, it failed with:

ValueError: No agents loaded successfully

agent.config_error: Agent is not an instance or a descendant of BaseAgent, bound=BaseAgent! It will be discarded

The just-agents/examples/notebooks directory has some documentation, but for a first-time user like me, it’s not immediately clear how to get started without a working YAML example.

Best regards,
Zongmin
